#!/usr/bin/env python
#
# 2025-05-09: Initial version by TG Gowda
#
"""
 Report scores for WMT26 model-compression runs

This script reads the score files generated by the evaluation pipeline and
prints the scores in a tabular format.
"""
import argparse
from pathlib import Path

from modelzip.config import LOG, WORK_DIR


def report(work_dir: Path, fmt: str = "tsv"):
    work_dir = Path(work_dir)
    score_files = work_dir.glob("tests/*/*.score")
    rows = []
    for sf in score_files:
        if sf.stat().st_size == 0:
            LOG.warning(f"Empty score file {sf}")
            continue
        tag = sf.name.replace(".score", "")
        score = sf.read_text().strip()
        rows.append((tag, score))
    rows.sort()
    delim = "\t" if fmt == "tsv" else ","
    for tag, score in rows:
        print(delim.join((tag, score)))


def main():
    parser = argparse.ArgumentParser(description="Report scores for WMT26 model-compression runs")
    parser.add_argument("-w", "--work", type=Path, default=WORK_DIR, help="Working directory")
    parser.add_argument("-f", "--format", choices=["csv", "tsv"], default="tsv", help="Output format")
    args = parser.parse_args()
    report(work_dir=args.work, fmt=args.format)


if __name__ == "__main__":
    main()
